### ISSUE TITLE
Error during installation pip3 

### ISSUE THREAD

**Issue by JavierRuano** [sfox14/pynq-sklearn#1]
pip3 install git+https://github.com/sfox14/pynq-sklearn.git  
Cloning https://github.com/sfox14/pynq-sklearn.git to /tmp/pip-n8_l31qn-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-n8_l31qn-build/setup.py", line 7, in <module>
        import pynq_sklearn
      File "/tmp/pip-n8_l31qn-build/pynq_sklearn/__init__.py", line 4, in <module>
        from . import linear_model, random_projection
      File "/tmp/pip-n8_l31qn-build/pynq_sklearn/linear_model/__init__.py", line 1, in <module>
        from .linear import PynqLinearRegression
      File "/tmp/pip-n8_l31qn-build/pynq_sklearn/linear_model/linear.py", line 13, in <module>
        from sklearn.linear_model import LinearRegression
    ModuleNotFoundError: No module named 'sklearn'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-n8_l31qn-build/

**Comment by JavierRuano** [comment]
If i install sklearn with apt.
 pip3 install git+https://github.com/sfox14/pynq-sklearn.git --upgrade 
it works.
But it has another problems as 
sklearn/logistic_notebook.ipynb
>>> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-48e97e0e130d>", line 7, in <module>
    lib = HybridLibrary(**args)
  File "/usr/local/lib/python3.6/dist-packages/pynq_sklearn/register.py", line 140, in __init__
    Registry.check_lib(self)
  File "/usr/local/lib/python3.6/dist-packages/pynq_sklearn/register.py", line 163, in check_lib
    %arg)
AttributeError: HybridLibrary requires attribute: library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1483, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1441, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.6/posixpath.py", line 376, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by sfox14** [comment]
What version of PYNQ were you using? This repo was built for v2.1. 

Sorry for the late reply. I will be updating this repo shortly and incorporating some new work for the latest PYNQ image.

**Comment by JavierRuano** [comment]
That one, the lastest

**Comment by sfox14** [comment]
Ok good. 

The error is the same as described in cell 1 of "sklearn/hybrid_library.ipynb". This is the expected behaviour for that notebook. 

I can not replicate that error in logistic_regression.ipynb. 

Also how are you executing the code. I usually use jupyter in the browser.
